# Generated by Django 5.1.4 on 2025-01-11 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_contactlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='phone_book',
            field=models.CharField(blank=True, choices=[('group1', 'Group 1'), ('group2', 'Group 2'), ('group3', 'Group 3'), ('group4', 'Group 4'), ('group5', 'Group 5')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='schedule_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='send_option',
            field=models.CharField(choices=[('now', 'Now'), ('later', 'Later')], default='now', max_length=50),
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='sender_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='type_recipients',
            field=models.CharField(blank=True, choices=[('group', 'Group'), ('individual', 'Individual')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='SentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=255)),
                ('recipients', models.TextField()),
                ('message', models.TextField()),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Sent', max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
