# Generated by Django 5.1.4 on 2025-01-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_transaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmessage',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('sent', 'Sent')], default='draft', max_length=10),
        ),
    ]
